
(rule
 (action
  (write-file link_flags.txt "(-ccopt -Wl,-no_warn_duplicate_libraries)")
 )
 (enabled_if (= %{system} macosx))
)

(rule
 (action
  (write-file link_flags.txt "()")
 )
 (enabled_if (<> %{system} macosx))
)

(executable
 (public_name parsesrc_.exe)
 (name parsesrc)
 (package diffast-cli)
 (modules parsesrc)
 (libraries threads dynlink diffast-api vlt)
 (link_flags (:include link_flags.txt))
 (preprocess
  (pps vlt.ppx -- -level %{env:DIFFAST_LOG_LEVEL=WARN}))
)

(executable
 (public_name simast_.exe)
 (name simast)
 (package diffast-cli)
 (modules simast)
 (libraries threads dynlink diffast-api vlt)
 (link_flags (:include link_flags.txt))
 (preprocess
  (pps vlt.ppx -- -level %{env:DIFFAST_LOG_LEVEL=WARN}))
)

(executable
 (public_name diffast_.exe)
 (name diffast)
 (package diffast-cli)
 (modules diffast)
 (libraries threads dynlink diffast-api vlt)
 (link_flags (:include link_flags.txt))
 (preprocess
  (pps vlt.ppx -- -level %{env:DIFFAST_LOG_LEVEL=WARN}))
)

(executable
 (public_name patchast_.exe)
 (name patchast)
 (package diffast-cli)
 (modules patchast)
 (libraries threads dynlink diffast-api vlt)
 (link_flags (:include link_flags.txt))
 (preprocess
  (pps vlt.ppx -- -level %{env:DIFFAST_LOG_LEVEL=WARN}))
)

(install
 (section bin)
 (files
  parsesrc parsesrc-debug
  simast simast-debug
  diffast diffast-debug
  patchast patchast-debug
 )
 (package diffast-cli)
)
